; Nyquistを日本語配列設定の端末に繋げてもそのまま使えるようキーリマップ
*"::send, @
*&::send, {^}
*'::send, &
*(::send, *
*)::send, (
*+0::send, )
*=::send, _
*^::send, =
*~::send, {+}
*@::send, [
*`::send, {{}
*[::send, ]
*{::send, {}}
*]::send, \
*}::send, |
*+::send, :
+*::send, "
*vkBA::send, '
*vkF3sc029::send, {``}
*vkF4sc029::send, {``}
+vkF3sc029::send, ~
+vkF4sc029::send, ~
